[build]
  publish = "build"         # this is where React's production build outputs
  functions = "netlify/functions"  # path to your serverless functions


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
